package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type structInfo struct {
	Name   string
	Struct *ast.StructType
}

type resetTemplateData struct {
	StructName string
	Fields     []string
}

var resetTemplate = template.Must(template.New("reset").Parse(`
func (s *{{.StructName}}) Reset() {
	if s == nil {
		return
	}
{{- range .Fields}}
	{{.}}
{{- end}}
}
`))

func main() {
	root := "."

	packages := map[string][]structInfo{}
	pkgNames := map[string]string{}

	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			if d.Name() == ".git" || d.Name() == "vendor" || strings.Contains(path, "cmd/reset") {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, ".gen.go") {
			return nil
		}

		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return err
		}

		dir := filepath.Dir(path)
		pkgNames[dir] = file.Name.Name

		for _, decl := range file.Decls {

			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Doc == nil {
				continue
			}

			if !hasResetComment(gen.Doc) {
				continue
			}

			for _, spec := range gen.Specs {

				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}

				packages[dir] = append(packages[dir], structInfo{
					Name:   ts.Name.Name,
					Struct: st,
				})
			}
		}

		return nil
	})

	if err != nil {
		log.Fatal(err)
	}

	for dir, structs := range packages {

		pkgName := pkgNames[dir]

		var code strings.Builder

		for _, s := range structs {
			code.WriteString(generateReset(s))
			code.WriteString("\n")
		}

		err := writeFile(dir, pkgName, code.String())
		if err != nil {
			log.Fatal(err)
		}
	}
}

func hasResetComment(cg *ast.CommentGroup) bool {
	for _, c := range cg.List {
		if strings.Contains(c.Text, "generate:reset") {
			return true
		}
	}
	return false
}

func generateReset(s structInfo) string {

	var fields []string

	for _, field := range s.Struct.Fields.List {

		if len(field.Names) == 0 {
			continue
		}

		for _, n := range field.Names {

			name := n.Name

			switch t := field.Type.(type) {

			case *ast.Ident:

				switch t.Name {

				case "int", "int8", "int16", "int32", "int64",
					"uint", "uint8", "uint16", "uint32", "uint64",
					"float32", "float64":

					fields = append(fields, fmt.Sprintf("s.%s = 0", name))

				case "string":

					fields = append(fields, fmt.Sprintf(`s.%s = ""`, name))

				case "bool":

					fields = append(fields, fmt.Sprintf("s.%s = false", name))

				default:

					fields = append(fields, fmt.Sprintf(`
if resetter, ok := any(&s.%s).(interface{ Reset() }); ok {
	resetter.Reset()
}`, name))
				}

			case *ast.ArrayType:

				fields = append(fields, fmt.Sprintf("s.%s = s.%s[:0]", name, name))

			case *ast.MapType:

				fields = append(fields, fmt.Sprintf("clear(s.%s)", name))

			case *ast.StarExpr:

				fields = append(fields, fmt.Sprintf(`
if s.%s != nil {
	if resetter, ok := any(s.%s).(interface{ Reset() }); ok {
		resetter.Reset()
	}
}`, name, name))
			}
		}
	}

	data := resetTemplateData{
		StructName: s.Name,
		Fields:     fields,
	}

	var buf strings.Builder
	if err := resetTemplate.Execute(&buf, data); err != nil {
		log.Fatal(err)
	}

	return buf.String()
}

func writeFile(dir string, pkg string, code string) error {

	var b strings.Builder

	b.WriteString("// Code generated by reset generator. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	b.WriteString(code)

	path := filepath.Join(dir, "reset.gen.go")

	return os.WriteFile(path, []byte(b.String()), 0644)
}
