package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

type structInfo struct {
	Name   string
	Struct *ast.StructType
}

func main() {
	root := "."

	packages := map[string][]structInfo{}
	pkgNames := map[string]string{}

	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			if d.Name() == ".git" || d.Name() == "vendor" || strings.Contains(path, "cmd/reset") {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, ".gen.go") {
			return nil
		}

		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return err
		}

		dir := filepath.Dir(path)
		pkgNames[dir] = file.Name.Name

		for _, decl := range file.Decls {

			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Doc == nil {
				continue
			}

			if !hasResetComment(gen.Doc) {
				continue
			}

			for _, spec := range gen.Specs {

				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}

				packages[dir] = append(packages[dir], structInfo{
					Name:   ts.Name.Name,
					Struct: st,
				})
			}
		}

		return nil
	})

	if err != nil {
		panic(err)
	}

	for dir, structs := range packages {

		pkgName := pkgNames[dir]

		var code strings.Builder

		for _, s := range structs {
			code.WriteString(generateReset(s))
			code.WriteString("\n")
		}

		err := writeFile(dir, pkgName, code.String())
		if err != nil {
			panic(err)
		}
	}
}

func hasResetComment(cg *ast.CommentGroup) bool {
	for _, c := range cg.List {
		if strings.Contains(c.Text, "generate:reset") {
			return true
		}
	}
	return false
}

func generateReset(s structInfo) string {

	var b strings.Builder

	fmt.Fprintf(&b, "func (s *%s) Reset() {\n", s.Name)
	b.WriteString("if s == nil { return }\n")

	for _, field := range s.Struct.Fields.List {

		if len(field.Names) == 0 {
			continue
		}

		name := field.Names[0].Name

		switch t := field.Type.(type) {

		case *ast.Ident:

			switch t.Name {

			case "int", "int8", "int16", "int32", "int64",
				"uint", "uint8", "uint16", "uint32", "uint64",
				"float32", "float64":

				fmt.Fprintf(&b, "s.%s = 0\n", name)

			case "string":

				fmt.Fprintf(&b, "s.%s = \"\"\n", name)

			case "bool":

				fmt.Fprintf(&b, "s.%s = false\n", name)

			default:

				fmt.Fprintf(&b, `
if resetter, ok := any(&s.%s).(interface{ Reset() }); ok {
	resetter.Reset()
}
`, name)
			}

		case *ast.ArrayType:

			fmt.Fprintf(&b, "s.%s = s.%s[:0]\n", name, name)

		case *ast.MapType:

			fmt.Fprintf(&b, "clear(s.%s)\n", name)

		case *ast.StarExpr:

			fmt.Fprintf(&b, `
if s.%s != nil {
	if resetter, ok := any(s.%s).(interface{ Reset() }); ok {
		resetter.Reset()
	}
}
`, name, name)
		}
	}

	b.WriteString("}\n")

	return b.String()
}

func writeFile(dir string, pkg string, code string) error {

	var b strings.Builder

	b.WriteString("// Code generated by reset generator. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	b.WriteString(code)

	path := filepath.Join(dir, "reset.gen.go")

	return os.WriteFile(path, []byte(b.String()), 0644)
}
